name: recsys-conda
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - anyio=4.5.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.4
  - attrs=24.2.0
  - babel=2.16.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.3
  - bleach=6.1.0
  - brotli-python=1.0.9
  - ca-certificates=2025.10.5
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2024.8.30
  - cffi=1.15.0
  - charset-normalizer=3.4.0
  - comm=0.2.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - fqdn=1.5.1
  - h11=0.14.0
  - h2=4.1.0
  - hpack=4.0.0
  - httpcore=1.0.7
  - httpx=0.27.2
  - hyperframe=6.0.1
  - idna=3.10
  - importlib-metadata=8.5.0
  - importlib_resources=6.4.5
  - ipykernel=6.29.5
  - ipython=8.12.2
  - ipywidgets=8.1.5
  - isoduration=20.11.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - json5=0.9.25
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter=1.1.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.10.0
  - jupyter_server=2.14.2
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.3.0
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.13
  - ld_impl_linux-64=2.44
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=11.2.0
  - liblapack=3.9.0
  - libopenblas=0.3.30
  - libsodium=1.0.20
  - libstdcxx-ng=11.2.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.7
  - mistune=3.0.2
  - nbclient=0.10.2
  - nbconvert-core=7.16.4
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - notebook=7.0.6
  - notebook-shim=0.2.4
  - numpy=1.22.3
  - openssl=3.0.18
  - overrides=7.7.0
  - packaging=25.0
  - pandas=1.4.2
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - prometheus_client=0.21.0
  - prompt-toolkit=3.0.48
  - prompt_toolkit=3.0.48
  - psutil=5.9.1
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.18.0
  - pysocks=1.7.1
  - python=3.8.20
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.20.0
  - python-json-logger=2.0.7
  - python_abi=3.8
  - pytz=2024.2
  - pyyaml=6.0
  - pyzmq=25.1.2
  - readline=8.3
  - referencing=0.35.1
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - scikit-surprise=1.1.1
  - send2trash=1.8.3
  - setuptools=75.1.0
  - six=1.16.0
  - sniffio=1.3.1
  - soupsieve=2.6
  - sqlite=3.50.2
  - stack_data=0.6.2
  - terminado=0.18.1
  - tinycss2=1.4.0
  - tk=8.6.15
  - tomli=2.0.2
  - tornado=6.4.1
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20241003
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - uri-template=1.3.0
  - urllib3=2.2.3
  - wcwidth=0.2.13
  - webcolors=24.8.0
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.44.0
  - widgetsnbextension=4.0.13
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
prefix: /home/helin/miniconda3/envs/recsys-conda
