name: recsys-conda
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - anyio=4.5.0=pyhd8ed1ab_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py38h0a891b7_2
  - arrow=1.3.0=pyhd8ed1ab_0
  - arrow-cpp=16.1.0=hc1eb8f0_0
  - asttokens=3.0.0=pyhd8ed1ab_0
  - async-lru=2.0.4=pyhd8ed1ab_0
  - attrs=24.2.0=pyh71513ae_0
  - aws-c-auth=0.6.19=h5eee18b_0
  - aws-c-cal=0.5.20=hdbd6064_0
  - aws-c-common=0.8.5=h5eee18b_0
  - aws-c-compression=0.2.16=h5eee18b_0
  - aws-c-event-stream=0.2.15=h6a678d5_0
  - aws-c-http=0.6.25=h5eee18b_0
  - aws-c-io=0.13.10=h5eee18b_0
  - aws-c-mqtt=0.7.13=h5eee18b_0
  - aws-c-s3=0.1.51=hdbd6064_0
  - aws-c-sdkutils=0.1.6=h5eee18b_0
  - aws-checksums=0.1.13=h5eee18b_0
  - aws-crt-cpp=0.18.16=h6a678d5_0
  - aws-sdk-cpp=1.10.55=h721c034_0
  - babel=2.16.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - beautifulsoup4=4.12.3=pyha770c72_0
  - blas=2.138=openblas
  - blas-devel=3.9.0=38_h1ea3ea9_openblas
  - bleach=6.1.0=pyhd8ed1ab_0
  - brotli=1.0.9=h9c3ff4c_4
  - brotli-python=1.0.9=py38hfa26641_7
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.15.0=py38h3931269_0
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.0.2=py38h43d8883_2
  - cycler=0.12.1=pyhd8ed1ab_0
  - cyrus-sasl=2.1.28=h1110e0f_3
  - dbus=1.16.2=h5bd4931_0
  - debugpy=1.6.7=py38h6a678d5_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - expat=2.7.1=h6a678d5_0
  - fontconfig=2.15.0=h2c49b7f_0
  - fonttools=4.33.3=py38h0a891b7_0
  - fqdn=1.5.1=pyhd8ed1ab_0
  - freetype=2.13.3=h4a9f257_0
  - gettext=0.21.0=hedfda30_2
  - gflags=2.2.2=h6a678d5_1
  - glib=2.84.4=h5bdd934_0
  - glib-tools=2.84.4=h8875d55_0
  - glog=0.5.0=h6a678d5_1
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - h11=0.14.0=pyhd8ed1ab_0
  - h2=4.1.0=pyhd8ed1ab_0
  - hpack=4.0.0=pyh9f0ad1d_0
  - httpcore=1.0.7=pyh29332c3_1
  - httpx=0.27.2=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=73.1=h6a678d5_0
  - idna=3.10=pyhd8ed1ab_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.12.2=pyh41d4057_0
  - ipywidgets=8.1.5=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_0
  - jbig=2.1=h7f98852_2003
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_1
  - json5=0.9.25=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py38h578d9bd_0
  - jsonschema=4.23.0=pyhd8ed1ab_0
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_1
  - jupyter=1.1.1=pyhd8ed1ab_0
  - jupyter-lsp=2.2.5=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_0
  - jupyter_console=6.6.3=pyhd8ed1ab_0
  - jupyter_core=5.8.1=pyh31011fe_0
  - jupyter_events=0.10.0=pyhd8ed1ab_0
  - jupyter_server=2.14.2=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_0
  - jupyterlab=4.3.0=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_1
  - jupyterlab_server=2.27.3=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.13=pyhd8ed1ab_0
  - kiwisolver=1.4.2=py38h43d8883_1
  - krb5=1.20.1=h143b758_1
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=3.0=h9c3ff4c_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libblas=3.9.0=38_h4a7cf45_openblas
  - libbrotlicommon=1.0.9=h5eee18b_9
  - libbrotlidec=1.0.9=h5eee18b_9
  - libbrotlienc=1.0.9=h5eee18b_9
  - libcblas=3.9.0=38_h0358290_openblas
  - libclang=14.0.6=default_hc6dbbc7_2
  - libclang13=14.0.6=default_he11475f_2
  - libcups=2.4.2=h252cb56_2
  - libcurl=8.16.0=heebcbe5_0
  - libdeflate=1.10=h7f98852_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=13.2.0=h69a702a_0
  - libgfortran5=13.2.0=ha4646dd_0
  - libglib=2.84.4=h77a78f3_0
  - libgomp=11.2.0=h1234567_1
  - libgrpc=1.62.2=h2d74bed_0
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.8=hf80d704_0
  - libkrb5=1.21.3=h520c7b4_4
  - liblapack=3.9.0=38_h47877c9_openblas
  - liblapacke=3.9.0=38_h6ae95b6_openblas
  - libllvm14=14.0.6=hecde1de_4
  - libnghttp2=1.57.0=h2d74bed_0
  - libopenblas=0.3.30=h46f56fc_0
  - libpng=1.6.50=h2ed474d_0
  - libpq=17.6=ha51bf15_0
  - libprotobuf=4.25.3=he621ea3_0
  - libsodium=1.0.20=heac8642_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libthrift=0.15.0=hd8eb582_4
  - libtiff=4.3.0=h542a066_3
  - libunistring=1.3=hb25bd0a_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - lmdb=0.9.29=h166bdaf_1
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.1=py38h0a891b7_1
  - matplotlib=3.7.2=py38h578d9bd_0
  - matplotlib-base=3.7.2=py38h1128e8f_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mistune=3.0.2=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql=8.4.0=h29a9f33_1
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.4=pyhff2d567_2
  - nbformat=5.10.4=pyhd8ed1ab_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - nomkl=3.0=0
  - notebook=7.0.6=py38h06a4308_0
  - notebook-shim=0.2.4=pyhd8ed1ab_0
  - numpy=1.22.3=py38h99721a1_2
  - openblas=0.3.30=h5426c36_0
  - openblas-devel=0.3.30=h557178c_0
  - openjpeg=2.4.0=h9ca470c_2
  - openldap=2.6.10=he9288cc_1
  - openssl=3.0.18=hd6dcaed_0
  - orc=2.0.1=h2d29ad5_0
  - overrides=7.7.0=pyhd8ed1ab_0
  - packaging=25.0=pyh29332c3_1
  - pandas=1.4.2=py38h47df419_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - patsy=0.5.6=pyhd8ed1ab_0
  - pcre2=10.46=hf426167_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.4.0=py38h5eee18b_0
  - pip=24.2=py38h06a4308_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - pooch=1.8.2=pyhd8ed1ab_0
  - prometheus_client=0.21.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.48=pyha770c72_0
  - prompt_toolkit=3.0.48=hd8ed1ab_1
  - psutil=5.9.1=py38h0a891b7_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pyarrow=16.1.0=py38h1128e8f_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyqt=5.15.4=py38hfa26641_0
  - pyqt5-sip=12.9.0=py38hfa26641_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.8.20=he870216_0
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-fastjsonschema=2.20.0=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytz=2024.2=pyhd8ed1ab_0
  - pyyaml=6.0=py38h0a891b7_4
  - pyzmq=25.1.2=py38h6a678d5_0
  - qt-main=5.15.2=hb6262e9_12
  - re2=2022.04.01=h295c915_0
  - readline=8.3=hc2a1206_0
  - referencing=0.35.1=pyhd8ed1ab_0
  - requests=2.32.3=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rpds-py=0.10.6=py38hb02cf49_0
  - s2n=1.3.27=hdbd6064_0
  - scikit-learn=1.1.1=py38hf80bbf7_0
  - scikit-surprise=1.1.1=py38h6c62de6_2
  - scipy=1.10.1=py38h32ae08f_1
  - seaborn=0.13.2=hd8ed1ab_2
  - seaborn-base=0.13.2=pyhd8ed1ab_2
  - send2trash=1.8.3=pyh0d859eb_0
  - setuptools=75.1.0=py38h06a4308_0
  - sip=6.5.1=py38h709712a_2
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.2.1=h6a678d5_0
  - sniffio=1.3.1=pyhd8ed1ab_0
  - soupsieve=2.6=pyhd8ed1ab_0
  - sqlite=3.50.2=hb25bd0a_1
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.13.2=py38h6c62de6_0
  - terminado=0.18.1=pyh0d859eb_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.15=h54e0aa7_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.2=pyhd8ed1ab_0
  - tornado=6.4.1=py38h5eee18b_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - types-python-dateutil=2.9.0.20241003=pyhff2d567_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - tzdata=2025b=h04d1e81_0
  - unicodedata2=14.0.0=py38h0a891b7_1
  - uri-template=1.3.0=pyhd8ed1ab_0
  - urllib3=2.2.3=pyhd8ed1ab_0
  - utf8proc=2.6.1=h5eee18b_1
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - webcolors=24.8.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - websocket-client=1.8.0=pyhd8ed1ab_0
  - wheel=0.44.0=py38h06a4308_0
  - widgetsnbextension=4.0.13=pyhd8ed1ab_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.5=hb0a5e54_1
  - zipp=3.21.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb25bd0a_0
  - zstandard=0.23.0=py38h2c38b39_0
  - zstd=1.5.6=hc292b87_0
prefix: /home/helin/miniconda3/envs/recsys-conda
